### ISSUE TITLE
yargs-parser vulnerabilities 

### ISSUE THREAD

**Issue by akoushke** [xzyfer/sass-graph#108]
can you please update your packages? 
![02_11_59](https://user-images.githubusercontent.com/14226615/80846221-6607f280-8bc0-11ea-93c2-6b9dcd85b6c8.jpg)

help a homie out :)

**Comment by ruettenm** [comment]
Would be great to get a fix soon 👍

**Comment by thomas-mcdonald** [comment]
hey @xzyfer - I see node-sass attempts to keep a huge amount of node backcompat but there are no patched versions of yargs with explicit support for < node 4.

I feel I've been staring at different version specifiers and dependency trees for so long I'm not sure of the best way forward. A possible option would be to split the cli-part of this repo out from the API? It seems there is no requirement to push yargs as a dependency down the tree for consumers that are only using this as an API.

**Comment by xzyfer** [comment]
Hey @thomas-mcdonald I've been giving this some thought also, hence the delayed patch. As you've said node-sass maintains BC back node 0.10 - however it does not utilise the sass-graph cli.

I have considered splitting out the cli function as you've also suggested but have decided against creating more ongoing work for myself. I think in this case we're ok to just bump the yargs dep. Node-sass BC should be fine since we shouldn't be excerising the yargs code paths.

**Comment by xzyfer** [comment]
Note well also want to bump yargs dependency on the V2 branch since that's the version line node-sass currently uses

**Comment by xzyfer** [comment]
Released as 3.0.5 and 2.2.5
